# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001 
  type: NodePort 

